"""Add scraper_interval and last_scraped_at to User model

Revision ID: 17b915551ac4
Revises: f39e95fe0845
Create Date: 2025-02-24 14:55:20.422531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b915551ac4'
down_revision = 'f39e95fe0845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scraper_interval', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_scraped_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_scraped_at')
        batch_op.drop_column('scraper_interval')

    # ### end Alembic commands ###
