"""Add scraped_fb_post table and FacebookPage to models

Revision ID: 1cbdbf19dfec
Revises: 17b915551ac4
Create Date: 2025-02-27 15:43:04.125178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cbdbf19dfec'
down_revision = '17b915551ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facebook_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_url', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraped_fb_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('page_name', sa.String(length=255), nullable=True),
    sa.Column('post_url', sa.String(length=500), nullable=True),
    sa.Column('post_text', sa.Text(), nullable=True),
    sa.Column('time_of_posting', sa.String(length=100), nullable=True),
    sa.Column('number_of_likes', sa.Integer(), nullable=True),
    sa.Column('number_of_comments', sa.Integer(), nullable=True),
    sa.Column('number_of_shares', sa.Integer(), nullable=True),
    sa.Column('first_post_picture', sa.String(length=500), nullable=True),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('posttitle', sa.String(length=500), nullable=True),
    sa.Column('chatgpt_output', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraped_fb_post')
    op.drop_table('facebook_page')
    # ### end Alembic commands ###
