"""Add Facebook language preference

Revision ID: 503814ec0fa1
Revises: 1cbdbf19dfec
Create Date: 2025-03-13 10:49:45.497644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503814ec0fa1'
down_revision = '1cbdbf19dfec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_language_facebook', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('preferred_language_facebook')

    # ### end Alembic commands ###
