"""Add ScrapedTweet model

Revision ID: f39e95fe0845
Revises: 60b2ce0aba32
Create Date: 2025-02-09 00:06:58.325780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39e95fe0845'
down_revision = '60b2ce0aba32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('lang', sa.String(length=10), nullable=True),
    sa.Column('retweet_count', sa.Integer(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('quote_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('author_username', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('chatgpt_title', sa.String(length=500), nullable=True),
    sa.Column('chatgpt_output', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraped_tweet')
    # ### end Alembic commands ###
